services:
  - name: app-web
    type: web
    runtime: node
    repo: https://github.com/menouaw/CloudY2S2
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: app-db
        property: connectionString


databases:
  - name: app-db
    region: frankfurt
    plan: free


